import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "arcgis_sdk_test",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <h1
          className="text-xl h-[7vh] border-b-2 bg-gray-400 text-white 
        p-3"
        >
          Comuni Italiani
        </h1>
        {children}
      </body>
    </html>
  );
}
